#!/bin/bash

PWDIR='/path_to_quantum_espresso/'
element='all'

# do not change after this line

work=./WORK
. $PWDIR/examples/environment_variables
BIN_DIR=$PWDIR/bin

mkdir $work >& /dev/null
mkdir PSEUDOPOTENTIALS >& /dev/null

. ../nc_ps_collection.job

. ../paw_ps_collection.job

. ../us_ps_collection.job

ld1_command="$PARA_PREFIX $BIN_DIR/ld1.x $PARA_POSTFIX"

echo "ld1_command =" $ld1_command

if [ $element = "all" ] ;
then

   \rm -f $work/* >& /dev/null
   for atom in *.in ; do
       echo -e "Making   $atom  ...\c"
       $ld1_command < $atom > $work/$atom.out
       echo '  Done' 
   done

else

   for atom in "$element"*.in ; do
       echo -e "Making   $atom  ...\c"
       $ld1_command < $atom > $work/$atom.out
       echo '  Done' 
   done

fi

\mv *.UPF PSEUDOPOTENTIALS
\mv *.in WORK
\rm -fr ld1* 
