#!/bin/bash

PWDIR='/path_to_quantum_espresso/'
element='all'

# do not change after this line. Uncomment the appropriate line if
# you want to test the additional PPs or to use a version of 
# QE < 5.0 (at your own risk).

work=./WORK
#  For QE < 5.0 
#. $PWDIR/example/environment_variables
#
. $PWDIR/environment_variables
BIN_DIR=$PWDIR/bin

mkdir $work >& /dev/null
mkdir PSEUDOPOTENTIALS >& /dev/null

. ../paw_ps_collection.job
. ../us_ps_collection.job

#  Uncomment the following line to generate the NC-PPs. Be very careful
#  these PPs are completely untested.
#
#. ../nc_ps_collection.job

#  Uncomment the following line to generate additional PAW data sets. Be
#  careful these PPs might have problems.
#
#. ../paw_ps_collection_tot.job

#  Uncomment the following line to generate additional PAW data sets. 
#  These are alternative data sets. 
#
#. ../paw_ps_collection_alt.job

#  Uncomment the following line to generate additional US-PPs. Be
#  careful these PPs might have problems.
#
#. ../us_ps_collection_tot.job

#  Uncomment the following line to generate additional US-PPs. 
#  These are alternative PPs
#
#. ../us_ps_collection_alt.job

ld1_command="$PARA_PREFIX $BIN_DIR/ld1.x $PARA_POSTFIX"

echo "ld1_command =" $ld1_command

if [ $element = "all" ] ;
then

   for atom in *.in ; do
       echo -e "Making   $atom  ...\c"
       $ld1_command < $atom > $work/$atom.out
       echo '  Done' 
   done

else

   for atom in "$element"*.in ; do
       echo -e "Making   $atom  ...\c"
       $ld1_command < $atom > $work/$atom.out
       echo '  Done' 
   done

fi

\mv *.UPF PSEUDOPOTENTIALS
\mv *.in WORK
