#!/bin/bash
#!
#! Copyright (C) 2013 Andrea Dal Corso 
#! This file is distributed under the terms of the
#! GNU General Public License. See the file `License'
#! in the root directory of the present distribution,
#! or http://www.gnu.org/copyleft/gpl.txt .
#!


. ./environment.job
psdir=./PSEUDOPOTENTIALS

cat > Ag.$fct-dn-kjpaw_psl.0.1.test.in << EOF
 &input
   title='Ag',
   zed=47.,
   rel=$nrel,
   config='[Kr] 4d9.5 5s1.5 5p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ag.$fct-dn-kjpaw_psl.0.1.UPF',
   nconf=5
   configts(1)='4d9.5 5s1.5 5p0',
   configts(2)='4d10 5s1 ',
   configts(3)='4d9.5 5s0.5 5p1.0',
   configts(4)='4d9 5s2 5p0',
   configts(5)='4d10. 5s0 5p0',
 /
EOF

if [ $nrel = 2 ]
then

cat > Al.$fct-n-kjpaw_psl.0.2.2.in << EOF
 &input
   title='Al',
   zed=13.0,
   rel=$nrel,
   config='[Ne] 3s2 3p1 3d-2.0 4f-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Al.$fct-n-kjpaw_psl.0.2.2.UPF',
   nconf=5
   configts(1)='3s2 3p1'
   configts(2)='3s2 3p0 3d0'
   configts(3)='3s1.5 3p0 3d0.5'
   configts(4)='3s1 3p2 '
   configts(5)='3s1 3p1 3d0'
 /
EOF

else

cat > Al.$fct-n-kjpaw_psl.0.1.test.in << EOF
 &input
   title='Al',
   zed=13.0,
   rel=$nrel,
   config='[Ne] 3s2 3p1 3d-2.0 4f-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Al.$fct-n-kjpaw_psl.0.1.UPF',
   nconf=5
   configts(1)='3s2 3p1'
   configts(2)='3s2 3p0 3d0'
   configts(3)='3s1.5 3p0 3d0.5'
   configts(4)='3s1 3p2 '
   configts(5)='3s1 3p1 3d0'
 /
EOF

fi

cat > Ar.$fct-n-kjpaw_psl.0.3.0.test.in << EOF
 &input
   title='Ar',
   zed=18.0,
   rel=$nrel,
   config='[Ar] 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ar.$fct-n-kjpaw_psl.0.3.0.UPF',
   nconf=5
   configts(1)='3s2 3p6'
   configts(2)='3s2 3p5 3d0'
   configts(3)='3s2 3p4 3d1'
   configts(4)='3s1 3p6 3d0'
   configts(5)='3s1 3p5 3d0.5'
 /
EOF

cat > As.$fct-n-kjpaw_psl.0.2.test.in << EOF
 &input
   title='As',
   zed=33.,
   rel=$nrel,
   config='[Ar] 3d10.0 4s2.0 4p3.0 4d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/As.$fct-n-kjpaw_psl.0.2.UPF',
   nconf=5,
   configts(1)='4s2 4p3'
   configts(2)='4s2 4p2 4d0'
   configts(3)='4s2 4p2 4d0.5'
   configts(4)='4s1 4p3 4d0'
   configts(5)='4s1 4p4'
 /
EOF

cat > Au.$fct-dn-kjpaw_psl.0.3.0.test.in << EOF
 &input
   title='Au',
   zed=79.,
   rel=$nrel,
   config='[Xe] 4f14 5d10.0 6s1.0 6p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Au.$fct-dn-kjpaw_psl.0.3.0.UPF',
   nconf=5
   configts(1)='5d10. 6s1 6p0',
   configts(2)='5d10. 6s0 6p0.5',
   configts(3)='5d10. 6s0 6p0',
   configts(4)='5d9.5  6s1 ',
   configts(5)='5d9.5  6s1 6p0',
 /
EOF

cat > B.$fct-n-kjpaw_psl.0.1.test.in << EOF
 &input
   title='B',
   zed=5.0,
   rel=$nrel,
   config='1s2.0 2s2.0 2p1.0 3d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/B.$fct-n-kjpaw_psl.0.1.UPF',
   nconf=5,
   configts(1)='2s2 2p1'
   configts(2)='2s2 2p1'
   configts(3)='2s2 2p0'
   configts(4)='2s1 2p2'
   configts(5)='2s1 2p1'
 /
EOF

#cat > Be.$fct-n-kjpaw_psl.0.2.test.in << EOF
# &input
#   title='Be',
#   zed=4.0,
#   rel=$nrel,
#   config='1s2 2s2.0 2p0.0 3d-2',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Be.$fct-n-kjpaw_psl.0.2.UPF',
#   nconf=5,
#   configts(1)='2s2'
#   configts(2)='2s1 2p1'
#   configts(3)='2s1 2p0'
#   configts(4)='2s0.5 2p1'
#   configts(5)='2s0.5 2p0'
# /
#EOF

cat > Bi.$fct-dn-kjpaw_psl.0.2.2.test.in << EOF
 &input
   title='Bi',
   zed=83.,
   rel=$nrel,
   config='[Xe] 4f14.0 5d10.0 6s2.0 6p3.0 6d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Bi.$fct-dn-kjpaw_psl.0.2.2.UPF',
   nconf=5,
   configts(1)='5d10 6s2 6p3'
   configts(2)='5d10 6s2 6p2 6d0'
   configts(3)='5d10 6s2 6p1.0 6d0'
   configts(4)='5d10 6s1 6p3.0 6d0'
   configts(5)='5d10 6s1 6p4.0 '
 /
EOF

cat > Br.$fct-n-kjpaw_psl.0.2.test.in << EOF
 &input
   title='Br',
   zed=35.,
   rel=$nrel,
   config='[Ar] 3d10.0 4s2.0 4p5.0 4d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Br.$fct-n-kjpaw_psl.0.2.UPF',
   nconf=5,
   configts(1)='4s2 4p5'
   configts(2)='4s2 4p4 4d0'
   configts(3)='4s1 4p5 4d0'
   configts(4)='4s1 4p4'
   configts(5)='4s1 4p6'
 /
EOF

cat > C.$fct-n-kjpaw_psl.0.1.test.in << EOF
 &input
   title='C',
   zed=6,
   rel=$nrel,
   config='[He] 2s2 2p2 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/C.$fct-n-kjpaw_psl.0.1.UPF',
   nconf=5,
   configts(1)='2s2 2p2'
   configts(2)='2s2 2p1'
   configts(3)='2s2 2p0'
   configts(4)='2s1 2p2'
   configts(5)='2s1 2p3'
 /
EOF

#cat > Cd.$fct-dn-kjpaw_psl.0.3.1.test.in << EOF
# &input
#   title='Cd',
#   zed=48.,
#   rel=$nrel,
#   config='[Kr] 4d9.5 5s2.0 5p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Cd.$fct-dn-kjpaw_psl.0.3.1.UPF',
#   nconf=5
#   configts(1)='4d9.5 5s2 5p0.5 ',
#   configts(2)='4d9.5 5s2 5p0',
#   configts(3)='4d10  5s2 5p0',
#   configts(4)='4d10  5s1 5p0',
#   configts(5)='4d9   5s2 5p0',
# /
#EOF

cat > Cl.$fct-n-kjpaw_psl.0.3.0.test.in << EOF
 &input
   title='Cl',
   zed=17,
   rel=$nrel,
   config='[Ne] 3s2 3p5 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Cl.$fct-n-kjpaw_psl.0.3.0.UPF',
   nconf=5
   configts(1)='3s2 3p5'
   configts(2)='3s2 3p4 3d0'
   configts(3)='3s2 3p3 3d0'
   configts(4)='3s1 3p5 3d0'
   configts(5)='3s1 3p6'
 /
EOF

cat > Cu.$fct-dn-kjpaw_psl.0.2.test.in << EOF
 &input
   title='Cu',
   zed=29.,
   rel=$nrel,
   config='[Ar] 3d9.5 4s1.5 4p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Cu.$fct-dn-kjpaw_psl.0.2.UPF',
   nconf=5
   configts(1)='3d9.5 4s1.5'
   configts(2)='3d9.5 4s1 4p0'
   configts(3)='3d10 4s1 4p0'
   configts(4)='3d9.5 4s0 4p0'
   configts(5)='3d9  4s2 4p0'
 /
EOF

cat > Fe.$fct-spn-kjpaw_psl.0.2.1.test.in << EOF
 &input
   title='Fe',
   zed=26.,
   rel=$nrel,
   config='[Ar] 4s2.0 3d6.0 4p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Fe.$fct-spn-kjpaw_psl.0.2.1.UPF',
   nconf=5
   configts(1)='3s2 3p6 3d6 4s2'
   configts(2)='3s2 3p6 3d6 4s1 4p0'
   configts(3)='3s2 3p6 3d6 4s1 4p1'
   configts(4)='3s2 3p6 3d7 4s1'
   configts(5)='3s2 3p6 3d7 4s0 4p1'
 /
EOF

cat > F.$fct-n-kjpaw_psl.0.1.test.in << EOF
 &input
   title='F',
   zed=9.0,
   rel=$nrel,
   config='1s2.0 2s2.0 2p5.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/F.$fct-n-kjpaw_psl.0.1.UPF',
   nconf=5
   configts(1)='2s2 2p5'
   configts(2)='2s2 2p4'
   configts(3)='2s2 2p3'
   configts(4)='2s1 2p5'
   configts(5)='2s1 2p6'
 /
EOF

cat > Ga.$fct-dn-kjpaw_psl.0.2.test.in << EOF
 &input
   title='Ga',
   zed=31.,
   rel=$nrel,
   config='[Ar] 3d10.0 4s2.0 4p1.0 4d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ga.$fct-dn-kjpaw_psl.0.2.UPF',
   nconf=5
   configts(1)='3d10.0 4s2 4p1'
   configts(2)='3d10.0 4s2 4p0 4d0'
   configts(3)='3d10.0 4s1 4p2'
   configts(4)='3d10.0 4s1 4p1 4d0'
   configts(5)='3d10.0 4s0 4p3'
 /
EOF

cat > Ge.$fct-dn-kjpaw_psl.0.3.1.test.in << EOF
 &input
   title='Ge',
   zed=32.,
   rel=$nrel,
   config='[Ar] 3d10.0 4s2.0 4p2.0 4d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ge.$fct-dn-kjpaw_psl.0.3.1.UPF',
   nconf=5
   configts(1)='3d10 4s2 4p2'
   configts(2)='3d10 4s2 4p1 4d0'
   configts(3)='3d10 4s2 4p0 4d0'
   configts(4)='3d10 4s1 4p2 4d0'
   configts(5)='3d10 4s1 4p3'
 /
EOF

cat > In.$fct-dn-kjpaw_psl.0.2.2.test.in << EOF
 &input
   title='In',
   zed=49.,
   rel=$nrel,
   config='[Kr] 4d10.0 5s2.0 5p1.0 5d-1',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/In.$fct-dn-kjpaw_psl.0.2.2.UPF',
   nconf=5
   configts(1)='4d10 5s2 5p1'
   configts(2)='4d10 5s2 5p0 5d0'
   configts(3)='4d10 5s2 5p0 5d0'
   configts(4)='4d10 5s1 5p2'
   configts(5)='4d10 5s1 5p1 5d0'
 /
EOF

#cat > Ir.$fct-n-kjpaw_psl.0.2.3.test.in << EOF
# &input
#   title='Ir',
#   zed=77.,
#   rel=$nrel,
#   config='[Xe] 4f14.0 5d7.0 6s2.0 6p0.0',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Ir.$fct-n-kjpaw_psl.0.2.3.UPF',
#   nconf=5
#   configts(1)='5d7 6s2',
#   configts(2)='5d7 6s1 6p0',
#   configts(3)='5d7 6s0 6p1',
#   configts(4)='5d6 6s2 6p0',
#   configts(5)='5d6 6s2 6p1',
# /
#EOF

cat > H.$fct-kjpaw_psl.0.1.test.in << EOF
 &input
   title='H',
   zed=1,
   rel=$nrel,
   config='1s1 2p-1 2s-1',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/H.$fct-kjpaw_psl.0.1.UPF',
   nconf=3
   configts(1)='1s1'
   configts(2)='1s0.5 2s0 2p0'
   configts(3)='1s0.0 2s0.5 2p0'
 /
EOF

cat > Hg.$fct-dn-kjpaw_psl.0.2.2.test.in << EOF
 &input
   title='Hg',
   zed=80.0,
   rel=$nrel,
   config='[Xe] 4f14. 5d10 6s2 6p-1',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Hg.$fct-dn-kjpaw_psl.0.2.2.UPF',
   nconf=5,
   configts(1)='5d10 6s2'
   configts(2)='5d10 6s1 6p0'
   configts(3)='5d10 6s0 6p1'
   configts(4)='5d9  6s2 6p0'
   configts(5)='5d9  6s1 6p0'
 /
EOF

#if [ $nrel = 2 ]
#then

#cat > I.$fct-n-kjpaw_psl.0.2.2.test.in << EOF
# &input
#   title='I',
#   zed=53.,
#   rel=$nrel,
#   config='[Kr] 4d10.0 5s2.0 5p5.0 5d-2.0',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/I.$fct-n-kjpaw_psl.0.2.2.UPF',
#   nconf=5
#   configts(1)='5s2 5p5'
#   configts(2)='5s2 5p4 5d0'
#   configts(3)='5s2 5p3 5d0'
#   configts(4)='5s2 5p2 5d0'
#   configts(5)='5s2 5p1'
# /
#EOF

#else

#cat > I.$fct-n-kjpaw_psl.0.2.test.in << EOF
# &input
#   title='I',
#   zed=53.,
#   rel=$nrel,
#   config='[Kr] 4d10.0 5s2.0 5p5.0 5d-2.0',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/I.$fct-n-kjpaw_psl.0.2.UPF',
#   nconf=5
#   configts(1)='5s2 5p5'
#   configts(2)='5s2 5p4 5d0'
#   configts(3)='5s2 5p3 5d0'
#   configts(4)='5s2 5p2 5d0'
#   configts(5)='5s2 5p1'
# /
#EOF
#fi

cat > Li.$fct-s-kjpaw_psl.0.2.1.test.in << EOF
 &input
   title='Li',
   zed=3.0,
   rel=$nrel,
   config='1s2 2s1 2p0 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Li.$fct-s-kjpaw_psl.0.2.1.UPF',
   nconf=4
   configts(1)='1s2 2s1'
   configts(2)='1s2 2s0.5 2p0'
   configts(3)='1s2 2s0 2p0'
   configts(4)='1s2 2s0 2p1'
 /
EOF

cat > Mo.$fct-spn-kjpaw_psl.0.3.0.test.in << EOF
 &input
   title='Mo',
   zed=42.0,
   rel=$nrel,
   config='[Kr] 4d5.0 5s1 5p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Mo.$fct-spn-kjpaw_psl.0.3.0.UPF',
   nconf=5
   configts(1)='4s2 4p6 4d5 5s1'
   configts(2)='4s2 4p6 4d5 5s0 5p0'
   configts(3)='4s2 4p6 4d6 5s0'
   configts(4)='4s2 4p6 4d4 5s2' 
   configts(5)='4s2 4p6 4d4 5s1 5p0'
 /
EOF

cat > Na.$fct-spn-kjpaw_psl.0.2.test.in << EOF
 &input
   title='Na',
   zed=11.0,
   rel=$nrel,
   config='[Ne] 3s0.5 3p0 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Na.$fct-spn-kjpaw_psl.0.2.UPF',
   nconf=4
   configts(1)='2s2 2p6 3s1'
   configts(2)='2s2 2p6 3s0.5 3p0'
   configts(3)='2s2 2p6 3s0 3p0.5'
   configts(4)='2s2 2p6 3s0 3p0'
 /
EOF

cat > Nb.$fct-spn-kjpaw_psl.0.3.0.test.in << EOF
 &input
   title='Nb',
   zed=41.0,
   rel=$nrel,
   config='[Kr] 4d4.0 5s1 5p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Nb.$fct-spn-kjpaw_psl.0.3.0.UPF',
   nconf=5
   configts(1)='4s2 4p6 4d4 5s1'
   configts(2)='4s2 4p6 4d4 5s0 5p1'
   configts(3)='4s2 4p6 4d4 5s0 5p0'
   configts(4)='4s2 4p6 4d3 5s2'
   configts(5)='4s2 4p6 4d5 5s0'
 /
EOF

cat > Ni.$fct-n-kjpaw_psl.0.1.test.in << EOF
 &input
   title='Ni',
   zed=28.,
   rel=$nrel,
   config='[Ar] 4s2 3d8 4p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ni.$fct-n-kjpaw_psl.0.1.UPF',
   nconf=5
   configts(1)='3d8 4s2'
   configts(2)='3d9 4s1'
   configts(3)='3d8 4s1 4p0'
   configts(4)='3d8 4s1 4p0.5'
   configts(5)='3d7.5 4s2 4p0'
 /
EOF

cat > N.$fct-n-kjpaw_psl.0.1.test.in << EOF
 &input
   title='N',
   zed=7.,
   rel=$nrel,
   config='[He] 2s2 2p3 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/N.$fct-n-kjpaw_psl.0.1.UPF',
   nconf=5,
   configts(1)='2s2 2p3'
   configts(2)='2s2 2p2'
   configts(3)='2s2 2p1'
   configts(4)='2s1 2p4'
   configts(5)='2s1 2p3'
 /
EOF

cat > O.$fct-n-kjpaw_psl.0.1.test.in << EOF
 &input
   title='O',
   zed=8,
   rel=$nrel,
   config='[He] 2s2 2p4 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/O.$fct-n-kjpaw_psl.0.1.UPF',
   nconf=5,
   configts(1)='2s2 2p4'
   configts(2)='2s2 2p3'
   configts(3)='2s2 2p2'
   configts(4)='2s1 2p5'
   configts(5)='2s1 2p4'
 /
EOF

cat > Pb.$fct-dn-kjpaw_psl.0.2.2.test.in << EOF
 &input
   title='Pb',
   zed=82.0,
   rel=$nrel,
   config='[Xe] 4f14 5d10 6s2 6p2 6d-1',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Pb.$fct-dn-kjpaw_psl.0.2.2.UPF',
   nconf=5
   configts(1)='5d10. 6s2 6p2'
   configts(2)='5d10. 6s2 6p1 6d0'
   configts(3)='5d10. 6s2 6p0 6d0'
   configts(4)='5d10. 6s1 6p3'
   configts(5)='5d10. 6s1 6p2 6d0'
 /
EOF

cat > Pd.$fct-n-kjpaw_psl.0.3.0.test.in << EOF
 &input
   title='Pd',
   zed=46.,
   rel=$nrel,
   config='[Kr] 4d10. 5s0. 5p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Pd.$fct-n-kjpaw_psl.0.3.0.UPF',
   nconf=5,
   configts(1)='4d10 5s0.0'
   configts(2)='4d9.5 5s0.5'
   configts(3)='4d9.5 5s0 5p0.5'
   configts(4)='4d9 5s1 5p0'
   configts(5)='4d9 5s0 5p1'
 /
EOF

cat > Pt.$fct-n-kjpaw_psl.0.1.test.in << EOF
 &input
   title='Pt',
   zed=78.,
   rel=$nrel,
   config='[Xe] 4f14 5d9.0 6s1.0 6p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Pt.$fct-n-kjpaw_psl.0.1.UPF',
   nconf=5,
   configts(1)='5d9 6s1 6p0'
   configts(2)='5d9 6s0 6p0'
   configts(3)='5d10 6s0'
   configts(4)='5d8 6s1 6p0'
   configts(5)='5d8 6s1 6p1'
 /
EOF

cat > P.$fct-n-kjpaw_psl.0.1.test.in << EOF
 &input
   title='P',
   zed=15.,
   rel=$nrel,
   config='[Ne] 3s2 3p3 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/P.$fct-n-kjpaw_psl.0.1.UPF',
   nconf=5
   configts(1)='3s2 3p3'
   configts(2)='3s2 3p2 3d0'
   configts(3)='3s1 3p3 3d0'
   configts(4)='3s1 3p2 3d0'
   configts(5)='3s0 3p4 3d0'
 /
EOF

cat > Rh.$fct-spn-kjpaw_psl.0.3.0.test.in << EOF
 &input
   title='Rh',
   zed=45.,
   rel=$nrel,
   config='[Kr] 4d8. 5s1.0 5p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Rh.$fct-spn-kjpaw_psl.0.3.0.UPF',
   nconf=5
   configts(1)='4s2 4p6 4d8 5s1',
   configts(2)='4s2 4p6 4d8 5s0 5p0',
   configts(3)='4s2 4p6 4d7 5s2 5p0',
   configts(4)='4s2 4p6 4d7 5s1 5p1',
   configts(5)='4s2 4p6 4d7 5s0 5p0',
 /
EOF

cat > S.$fct-n-kjpaw_psl.0.1.test.in << EOF
 &input
   title='S',
   zed=16,
   rel=$nrel,
   config='[Ne] 3s2 3p4 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/S.$fct-n-kjpaw_psl.0.1.UPF',
   nconf=5,
   configts(1)='3s2 3p4'
   configts(2)='3s2 3p3 3d0'
   configts(3)='3s2 3p2'
   configts(4)='3s1 3p4 3d0'
   configts(5)='3s1 3p5'
 /
EOF

cat > Sc.$fct-spn-kjpaw_psl.0.2.3.test.in << EOF
 &input
   title='Sc',
   zed=21.0,
   rel=$nrel,
   config='[Ar] 3d1.0 4s2 4p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Sc.$fct-spn-kjpaw_psl.0.2.3.UPF',
   nconf=5
   configts(1)='3s2 3p6 3d1 4s2'
   configts(2)='3s2 3p6 3d1 4s1 4p1' 
   configts(3)='3s2 3p6 3d1 4s1 4p0'
   configts(4)='3s2 3p6 3d0 4s2 4p0'
   configts(5)='3s2 3p6 3d0 4s1 4p1'
 /
EOF

cat > Se.$fct-n-kjpaw_psl.0.2.test.in << EOF
 &input
   title='Se',
   zed=34.,
   rel=$nrel,
   config='[Ar] 3d10.0 4s2.0 4p4.0 4d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Se.$fct-n-kjpaw_psl.0.2.UPF',
   nconf=5,
   configts(1)='4s2 4p4'
   configts(2)='4s2 4p3 4d0'
   configts(3)='4s1 4p5'
   configts(4)='4s1 4p4 4d0'
   configts(5)='4s1 4p4 4d0.5'
 /
EOF

cat > Si.$fct-n-kjpaw_psl.0.1.test.in << EOF
 &input
   title='Si',
   zed=14.0,
   rel=$nrel,
   config='[Ne] 3s2 3p2 3d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Si.$fct-n-kjpaw_psl.0.1.UPF',
   nconf=5,
   configts(1)='3s2 3p2'
   configts(2)='3s2 3p1 3d0'
   configts(3)='3s2 3p0 3d0'
   configts(4)='3s1 3p3'
   configts(5)='3s1 3p2 3d0'
 /
EOF

cat > Sn.$fct-dn-kjpaw_psl.0.2.test.in << EOF
 &input
   title='Sn',
   zed=50.,
   rel=$nrel,
   config='[Kr] 4d10.0 5s2.0 5p2.0 5d-1',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Sn.$fct-dn-kjpaw_psl.0.2.UPF',
   nconf=5,
   configts(1)='4d10 5s2 5p2'
   configts(2)='4d10 5s2 5p1 5d0'
   configts(3)='4d10 5s2 5p0'
   configts(4)='4d10 5s1 5p3'
   configts(5)='4d10 5s1 5p2 5d0'
 /
EOF

cat > Sr.$fct-spn-kjpaw_psl.0.2.3.test.in << EOF
 &input
   title='Sr',
   zed=38.0,
   rel=$nrel,
   config='[Kr] 4d0.0 5s2 5p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Sr.$fct-spn-kjpaw_psl.0.2.3.UPF',
   nconf=5
   configts(1)='4s2 4p6 5s2'
   configts(2)='4s2 4p6 5s1.5'
   configts(3)='4s2 4p6 5s1 5p1'
   configts(4)='4s2 4p6 5s1 5p0'
   configts(5)='4s2 4p6 5s1.75 5p0 4d0.25'
 /
EOF

cat > Ta.$fct-spn-kjpaw_psl.0.2.test.in << EOF
 &input
   title='Ta',
   zed=73.0,
   rel=$nrel,
   config='[Xe] 4f14 5d3.0 6s2 6p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ta.$fct-spn-kjpaw_psl.0.2.UPF',
   nconf=5,
   configts(1)='5s2 5p6 5d3 6s2 6p0'
   configts(2)='5s2 5p6 5d3 6s1 6p1'
   configts(3)='5s2 5p6 5d3 6s1 6p0'
   configts(4)='5s2 5p6 5d2 6s2 6p0'
   configts(5)='5s2 5p6 5d2 6s1 6p1'
 /
EOF

cat > Tc.$fct-spn-kjpaw_psl.0.3.0.test.in << EOF
 &input
   title='Tc',
   zed=43.0,
   rel=$nrel,
   config='[Kr] 4d5.0 5s2 5p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Tc.$fct-spn-kjpaw_psl.0.3.0.UPF',
   nconf=5
   configts(1)='4s2 4p6 4d5 5s2'
   configts(2)='4s2 4p6 4d5 5s1 5p1'
   configts(3)='4s2 4p6 4d5 5s1 5p0'
   configts(4)='4s2 4p6 4d4 5s2'
   configts(5)='4s2 4p6 4d6 5s1'
 /
EOF

cat > Te.$fct-dn-kjpaw_psl.0.3.1.test.in << EOF
 &input
   title='Te',
   zed=52.,
   rel=$nrel,
   config='[Kr] 4d10.0 5s2.0 5p4.00 5d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Te.$fct-dn-kjpaw_psl.0.3.1.UPF',
   nconf=5,
   configts(1)='4d10 5s2 5p4'
   configts(2)='4d10 5s2 5p3 5d0'
   configts(3)='4d10 5s2 5p2'
   configts(4)='4d10 5s1 5p5'
   configts(5)='4d10 5s1 5p4 5d0'
 /
EOF

cat > Tl.$fct-dn-kjpaw_psl.0.2.3.test.in << EOF
 &input
   title='Tl',
   zed=81.,
   rel=$nrel,
   config='[Xe] 4f14.0 5d10.0 6s2.0 6p1.0 6d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Tl.$fct-dn-kjpaw_psl.0.2.3.UPF',
   nconf=5,
   configts(1)='5d10 6s2 6p1'
   configts(2)='5d10 6s2 6p0 6d0'
   configts(3)='5d10 6s1 6p1'
   configts(4)='5d10 6s1 6p2'
   configts(5)='5d10 6s1 6p0'
 /
EOF

cat > Y.$fct-spn-kjpaw_psl.0.2.3.test.in << EOF
 &input
   title='Y',
   zed=39.0,
   rel=$nrel,
   config='[Kr] 4d1.0 5s2 5p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Y.$fct-spn-kjpaw_psl.0.2.3.UPF',
   nconf=5
   configts(1)='4s2 4p6 4d1 5s2'
   configts(2)='4s2 4p6 4d1 5s1 5p1'
   configts(3)='4s2 4p6 4d1 5s1 5p0'
   configts(4)='4s2 4p6 4d0 5s2 5p0'
   configts(5)='4s2 4p6 4d2 5s1'
 /
EOF

cat > Zn.$fct-dn-kjpaw_psl.0.2.2.test.in << EOF
 &input
   title='Zn',
   zed=30.,
   rel=$nrel,
   config='[Ar] 3d10. 4s2. 4p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Zn.$fct-dn-kjpaw_psl.0.2.2.UPF',
   nconf=5,
   configts(1)='3d10 4s2'
   configts(2)='3d10 4s1 4p0'
   configts(3)='3d10 4s0 4p1 '
   configts(4)='3d9.5 4s2. 4p0'
   configts(5)='3d9 4s2. 4p0'
 /
EOF

cat > Zr.$fct-spn-kjpaw_psl.0.2.3.test.in << EOF
 &input
   title='Zr',
   zed=40.0,
   rel=$nrel,
   config='[Kr] 4d2.0 5s2 5p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Zr.$fct-spn-kjpaw_psl.0.2.3.UPF',
   nconf=5
   configts(1)='4s2 4p6 4d2 5s2'
   configts(2)='4s2 4p6 4d2 5s1 5p1'
   configts(3)='4s2 4p6 4d2 5s1 5p0'
   configts(4)='4s2 4p6 4d1 5s2 5p0'
   configts(5)='4s2 4p6 4d3 5s1'
 /
EOF
