#!/bin/bash
#!
#! Copyright (C) 2010-2013 Andrea Dal Corso 
#! This file is distributed under the terms of the
#! GNU General Public License. See the file `License'
#! in the root directory of the present distribution,
#! or http://www.gnu.org/copyleft/gpl.txt .
#!

. ./environment.job
psdir=./PSEUDOPOTENTIALS

#cat > Ce.$fct-spdn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Ce',
#   zed=58.0,
#   rel=$nrel,
#   config='[Xe] 4f1 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Ce.$fct-spdn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5  5d1  '
#   configts(2)='5s2 5p6 6s2   6p0    5d1 '
#   configts(3)='5s2 5p6 6s2   6p1.   5d0  '
#   configts(4)='5s2 5p6 6s2   6p0.   5d0  '
#   configts(5)='5s2 5p6 6s1   6p0.   5d1  '
# /
#EOF
#
#cat > Pr.$fct-spdn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Pr',
#   zed=59.0,
#   rel=$nrel,
#   config='[Xe] 4f2.0 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Pr.$fct-spdn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d1'
#   configts(2)='5s2 5p6 6s2 6p0 5d1'
#   configts(3)='5s2 5p6 6s1 6p0. 5d1'
#   configts(4)='5s2 5p6 6s1 6p1. 5d1'
#   configts(5)='5s2 5p6 6s0 6p0. 5d1'
# /
#EOF
#
#cat > Nd.$fct-spdn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Nd',
#   zed=60.0,
#   rel=$nrel,
#   config='[Xe] 4f3.0 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Nd.$fct-spdn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d1'
#   configts(2)='5s2 5p6 6s2 6p0 5d1 '
#   configts(3)='5s2 5p6 6s1 6p1. 5d1'
#   configts(4)='5s2 5p6 6s1 6p0. 5d1'
#   configts(5)='5s2 5p6 6s0 6p1. 5d1'
# /
#EOF
#
#cat > Pm.$fct-spdn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Pm',
#   zed=61.0,
#   rel=$nrel,
#   config='[Xe] 4f4.0 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Pm.$fct-spdn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d1'
#   configts(2)='5s2 5p6 6s2 6p0 5d1'
#   configts(3)='5s2 5p6 6s1 6p0. 5d1'
#   configts(4)='5s2 5p6 6s1 6p1. 5d1'
#   configts(5)='5s2 5p6 6s0 6p1. 5d1'
# /
#EOF

#cat > Sm.$fct-spdn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Sm',
#   zed=62.0,
#   rel=$nrel,
#   config='[Xe] 4f5.0 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Sm.$fct-spdn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d1'
#   configts(2)='5s2 5p6 6s2 6p0 5d1'
#   configts(3)='5s2 5p6 6s1 6p0. 5d1'
#   configts(4)='5s2 5p6 6s1 6p1. 5d1'
#   configts(5)='5s2 5p6 6s0 6p1. 5d1'
# /
#EOF
#
#cat > Sm.$fct-spn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Sm',
#   zed=62.0,
#   rel=$nrel,
#   config='[Xe] 4f6.0 5d0.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Sm.$fct-spn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d0'
#   configts(2)='5s2 5p6 6s2 6p0 5d0'
#   configts(3)='5s2 5p6 6s1 6p1. 5d0'
#   configts(4)='5s2 5p6 6s1 6p0. 5d0'
#   configts(5)='5s2 5p6 6s0 6p1. 5d0'
# /
#EOF

#cat > Eu.$fct-spdn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Eu',
#   zed=63.0,
#   rel=$nrel,
#   config='[Xe] 4f6.0 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Eu.$fct-spdn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d1'
#   configts(2)='5s2 5p6 6s2 6p0 5d1'
#   configts(3)='5s2 5p6 6s1 6p0. 5d1'
#   configts(4)='5s2 5p6 6s1 6p1. 5d1'
#   configts(5)='5s2 5p6 6s0 6p1. 5d1'
# /
#EOF

#cat > Eu.$fct-spn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Eu',
#   zed=63.0,
#   rel=$nrel,
#   config='[Xe] 4f7.0 5d0.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Eu.$fct-spn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d0  '
#   configts(2)='5s2 5p6 6s2 6p0 5d0  '
#   configts(3)='5s2 5p6 6s1 6p0. 5d1  '
#   configts(4)='5s2 5p6 6s1 6p1. 5d0  '
#   configts(5)='5s2 5p6 6s1 6p0. 5d0  '
# /
#EOF
#
#cat > Gd.$fct-spdn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Gd',
#   zed=64.0,
#   rel=$nrel,
#   config='[Xe] 4f7.0 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Gd.$fct-spdn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d1 '
#   configts(2)='5s2 5p6 6s2 6p0 5d1 '
#   configts(3)='5s2 5p6 6s1 6p0. 5d1 '
#   configts(4)='5s2 5p6 6s1 6p1. 5d1 '
#   configts(5)='5s2 5p6 6s0 6p1. 5d1 '
# /
#EOF
#
#cat > Tb.$fct-spdn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Tb',
#   zed=65.0,
#   rel=$nrel,
#   config='[Xe] 4f8.0 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Tb.$fct-spdn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d1'
#   configts(2)='5s2 5p6 6s2 6p0 5d1'
#   configts(3)='5s2 5p6 6s1 6p0. 5d1'
#   configts(4)='5s2 5p6 6s1 6p1. 5d1'
#   configts(5)='5s2 5p6 6s0 6p1. 5d1'
# /
#EOF
#
#cat > Dy.$fct-spdn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Dy',
#   zed=66.0,
#   rel=$nrel,
#   config='[Xe] 4f9.0 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Dy.$fct-spdn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d1'
#   configts(2)='5s2 5p6 6s2 6p0 5d1'
#   configts(3)='5s2 5p6 6s1 6p0 5d1'
#   configts(4)='5s2 5p6 6s1 6p1 5d1'
#   configts(5)='5s2 5p6 6s0 6p1 5d1'
# /
#EOF
#
#cat > Ho.$fct-spdn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Ho',
#   zed=67.0,
#   rel=$nrel,
#   config='[Xe] 4f10.0 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Ho.$fct-spdn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d1'
#   configts(2)='5s2 5p6 6s2 6p0 5d1'
#   configts(3)='5s2 5p6 6s1 6p0. 5d1'
#   configts(4)='5s2 5p6 6s1 6p1. 5d1'
#   configts(5)='5s2 5p6 6s0 6p1. 5d1'
# /
#EOF
#
#cat > Er.$fct-spdn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Er',
#   zed=68.0,
#   rel=$nrel,
#   config='[Xe] 4f11 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Er.$fct-spdn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d1'
#   configts(2)='5s2 5p6 6s2 6p0 5d1'
#   configts(3)='5s2 5p6 6s1 6p0. 5d1'
#   configts(4)='5s2 5p6 6s1 6p1. 5d1'
#   configts(5)='5s2 5p6 6s0 6p1. 5d1.5'
# /
#EOF
#
#cat > Er.$fct-spn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Er',
#   zed=68.0,
#   rel=$nrel,
#   config='[Xe] 4f12 5d0.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Er.$fct-spn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d0'
#   configts(2)='5s2 5p6 6s2 6p0 5d0'
#   configts(3)='5s2 5p6 6s1 6p0. 5d0'
#   configts(4)='5s2 5p6 6s1 6p1. 5d0'
#   configts(5)='5s2 5p6 6s0 6p1. 5d0'
# /
#EOF

#cat > Tm.$fct-spdn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Tm',
#   zed=69.0,
#   rel=$nrel,
##   config='[Xe] 4f12 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Tm.$fct-spdn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d1'
#   configts(2)='5s2 5p6 6s2 6p0 5d1'
#   configts(3)='5s2 5p6 6s1 6p0. 5d1'
#   configts(4)='5s2 5p6 6s1 6p1. 5d1'
#   configts(5)='5s2 5p6 6s0 6p1. 5d1.5'
# /
#EOF
#
#cat > Yb.$fct-spdn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Yb',
#   zed=70.0,
#   rel=$nrel,
#   config='[Xe] 4f13.0 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Yb.$fct-spdn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d1'
#   configts(2)='5s2 5p6 6s2 6p0 5d1'
#   configts(3)='5s2 5p6 6s1 6p0. 5d1'
#   configts(4)='5s2 5p6 6s1 6p1. 5d1'
#   configts(5)='5s2 5p6 6s0 6p1. 5d1.5'
# /
#EOF
#
#cat > Yb.$fct-spn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Yb',
#   zed=70.0,
#   rel=$nrel,
#   config='[Xe] 4f14.0 5d0.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Yb.$fct-spn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d0'
#   configts(2)='5s2 5p6 6s2 6p0 5d0'
#   configts(3)='5s2 5p6 6s1 6p0. 5d1'
#   configts(4)='5s2 5p6 6s1 6p1. 5d0'
#   configts(5)='5s2 5p6 6s1 6p0. 5d0'
# /
#EOF

#cat > Lu.$fct-spdn-rrkjus_psl.0.3.1.test.in << EOF
# &input
#   title='Lu',
#   zed=71.0,
#   rel=$nrel,
#   config='[Xe] 4f14.0 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Lu.$fct-spdn-rrkjus_psl.0.3.1.UPF',
#   nconf=5,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d1 '
#   configts(2)='5s2 5p6 6s2 6p0 5d1 '
#   configts(3)='5s2 5p6 6s1 6p0. 5d1 '
#   configts(4)='5s2 5p6 6s1 6p1. 5d1 '
#   configts(5)='5s2 5p6 6s0 6p1. 5d1.5 '
# /
#EOF
