#!/bin/bash
#!
#! Copyright (C) 2013 Andrea Dal Corso 
#! This file is distributed under the terms of the
#! GNU General Public License. See the file `License'
#! in the root directory of the present distribution,
#! or http://www.gnu.org/copyleft/gpl.txt .
#!


. ./environment.job
psdir=./PSEUDOPOTENTIALS
frozen_core=.false.

cat > H.$fct-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='H',
   zed=1,
   rel=$nrel,
   config='1s1 2p-1 2s-1',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/H.$fct-rrkjus_psl.1.0.0.UPF',
   nconf=3
   frozen_core=$frozen_core,
   configts(1)='1s1'
   configts(2)='1s0.5 2s0 2p0'
   configts(3)='1s0.0 2s0.5 2p0'
 /
EOF

cat > He.$fct-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='He',
   zed=2.0,
   rel=$nrel,
   config='1s2 2s-2 2p-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/He.$fct-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='1s2'
   configts(2)='1s1.5 2p0'
   configts(3)='1s1.5 2s0'
   configts(4)='1s1.5 2s0.5'
   configts(5)='1s1.5 2s0 2p0.5'
 /
EOF

cat > Li.$fct-s-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Li',
   zed=3.0,
   rel=$nrel,
   config='1s2 2s1 2p0 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Li.$fct-s-rrkjus_psl.1.0.0.UPF',
   nconf=4
   frozen_core=$frozen_core,
   configts(1)='1s2 2s1'
   configts(2)='1s2 2s0.5 2p0'
   configts(3)='1s2 2s0 2p0'
   configts(4)='1s2 2s0 2p1'
 /
EOF

cat > Be.$fct-s-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Be',
   zed=4.0,
   rel=$nrel,
   config='[He] 2s2.0 2p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Be.$fct-s-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='1s2 2s2'
   configts(2)='1s2 2s1 2p1'
   configts(3)='1s2 2s1 2p0'
   configts(4)='1s2 2s0.5 2p1'
   configts(5)='1s2 2s0.5 2p0'
 /
EOF

cat > B.$fct-n-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='B',
   zed=5.0,
   rel=$nrel,
   config='1s2.0 2s2.0 2p1.0 3d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/B.$fct-n-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='2s2 2p1'
   configts(2)='2s2 2p1'
   configts(3)='2s2 2p0'
   configts(4)='2s1 2p2'
   configts(5)='2s1 2p1'
 /
EOF

cat > C.$fct-n-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='C',
   zed=6,
   rel=$nrel,
   config='[He] 2s2 2p2 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/C.$fct-n-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='2s2 2p2'
   configts(2)='2s2 2p1'
   configts(3)='2s2 2p0'
   configts(4)='2s1 2p2'
   configts(5)='2s1 2p3'
 /
EOF

cat > N.$fct-n-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='N',
   zed=7.,
   rel=$nrel,
   config='[He] 2s2 2p3 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/N.$fct-n-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='2s2 2p3'
   configts(2)='2s2 2p2'
   configts(3)='2s2 2p1'
   configts(4)='2s1 2p4'
   configts(5)='2s1 2p3'
 /
EOF

cat > O.$fct-n-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='O',
   zed=8,
   rel=$nrel,
   config='[He] 2s2 2p4 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/O.$fct-n-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='2s2 2p4'
   configts(2)='2s2 2p3'
   configts(3)='2s2 2p2'
   configts(4)='2s1 2p5'
   configts(5)='2s1 2p4'
 /
EOF

cat > F.$fct-n-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='F',
   zed=9.0,
   rel=$nrel,
   config='1s2.0 2s2.0 2p5.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/F.$fct-n-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='2s2 2p5'
   configts(2)='2s2 2p4'
   configts(3)='2s2 2p3'
   configts(4)='2s1 2p5'
   configts(5)='2s1 2p6'
 /
EOF

cat > Ne.$fct-n-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ne',
   zed=10.0,
   rel=$nrel,
   config='1s2 2s2 2p6 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ne.$fct-n-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='2s2 2p6'
   configts(2)='2s2 2p5 3d0 '
   configts(3)='2s2 2p5 3d0.5'
   configts(4)='2s1 2p6 3d0'
   configts(5)='2s1 2p5 3d0'
 /
EOF

cat > Na.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Na',
   zed=11.0,
   rel=$nrel,
   config='[Ne] 3s0.5 3p0 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Na.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=4
   frozen_core=$frozen_core,
   configts(1)='2s2 2p6 3s1'
   configts(2)='2s2 2p6 3s0.5 3p0'
   configts(3)='2s2 2p6 3s0 3p0.5'
   configts(4)='2s2 2p6 3s0 3p0'
 /
EOF

cat > Mg.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Mg',
   zed=12.0,
   rel=$nrel,
   config='[Ne] 3s2.0 3p0 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Mg.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='2s2 2p6 3s2'
   configts(2)='2s2 2p6 3s1.5 3p0'
   configts(3)='2s2 2p6 3s1 3p0.5'
   configts(4)='2s2 2p6 3s1 3p0'
   configts(5)='2s2 2p6 3s1 3p0'
 /
EOF

cat > Al.$fct-n-rrkjus_psl.1.0.0.in << EOF
 &input
   title='Al',
   zed=13.0,
   rel=$nrel,
   config='[Ne] 3s2 3p1 3d-2.0 4f-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Al.$fct-n-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3s2 3p1'
   configts(2)='3s2 3p0 3d0'
   configts(3)='3s1.5 3p0 3d0.5'
   configts(4)='3s1 3p2 '
   configts(5)='3s1 3p1 3d0'
 /
EOF

cat > Si.$fct-n-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Si',
   zed=14.0,
   rel=$nrel,
   config='[Ne] 3s2 3p2 3d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Si.$fct-n-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='3s2 3p2'
   configts(2)='3s2 3p1 3d0'
   configts(3)='3s2 3p0 3d0'
   configts(4)='3s1 3p3'
   configts(5)='3s1 3p2 3d0'
 /
EOF

cat > P.$fct-n-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='P',
   zed=15.,
   rel=$nrel,
   config='[Ne] 3s2 3p3 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/P.$fct-n-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3s2 3p3'
   configts(2)='3s2 3p2 3d0'
   configts(3)='3s1 3p3 3d0'
   configts(4)='3s1 3p2 3d0'
   configts(5)='3s0 3p4 3d0'
 /
EOF

cat > S.$fct-n-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='S',
   zed=16,
   rel=$nrel,
   config='[Ne] 3s2 3p4 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/S.$fct-n-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='3s2 3p4'
   configts(2)='3s2 3p3 3d0'
   configts(3)='3s2 3p2 3d0'
   configts(4)='3s1 3p4 3d0'
   configts(5)='3s1 3p5'
 /
EOF

cat > Cl.$fct-n-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Cl',
   zed=17,
   rel=$nrel,
   config='[Ne] 3s2 3p5 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Cl.$fct-n-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3s2 3p5'
   configts(2)='3s2 3p4 3d0'
   configts(3)='3s2 3p3 3d0'
   configts(4)='3s1 3p5 3d0'
   configts(5)='3s1 3p6'
 /
EOF

cat > Ar.$fct-n-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ar',
   zed=18.0,
   rel=$nrel,
   config='[Ar] 3d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ar.$fct-n-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3s2 3p6'
   configts(2)='3s2 3p5 3d0'
   configts(3)='3s2 3p4 3d1'
   configts(4)='3s1 3p6 3d0'
   configts(5)='3s1 3p5 3d0.5'
 /
EOF

cat > K.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='K',
   zed=19.0,
   rel=$nrel,
   config='[Ar] 3d-2 4s1 4p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/K.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3s2 3p6 4s1'
   configts(2)='3s2 3p6 4s0.5 4p0.5'
   configts(3)='3s2 3p6 4s0.5 3d0'
   configts(4)='3s2 3p6 4s0.5 4p0 '
   configts(5)='3s2 3p6 4s0.75 4p0 3d0.25'
 /
EOF

cat > Ca.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ca',
   zed=20.0,
   rel=$nrel,
   config='[Ar] 3d0.0 4s2.0 4p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ca.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3s2 3p6 4s2'
   configts(2)='3s2 3p6 4s1.5 4p0'
   configts(3)='3s2 3p6 4s1 4p0'
   configts(4)='3s2 3p6 4s1 4p1'
   configts(5)='3s2 3p6 4s1 4p0 3d1'
 /
EOF

cat > Sc.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Sc',
   zed=21.0,
   rel=$nrel,
   config='[Ar] 3d1.0 4s2 4p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Sc.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3s2 3p6 3d1 4s2'
   configts(2)='3s2 3p6 3d1 4s1 4p1' 
   configts(3)='3s2 3p6 3d1 4s1 4p0'
   configts(4)='3s2 3p6 3d0 4s2 4p0'
   configts(5)='3s2 3p6 3d0 4s1 4p1'
 /
EOF

cat > Ti.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ti',
   zed=22.0,
   rel=$nrel,
   config='[Ar] 3d2.0 4s2 4p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ti.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3s2 3p6 3d2 4s2'
   configts(2)='3s2 3p6 3d2 4s1 4p1'
   configts(3)='3s2 3p6 3d2 4s0 4p0'
   configts(4)='3s2 3p6 3d1 4s2 4p0'
   configts(5)='3s2 3p6 3d1 4s1'
 /
EOF

cat > V.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='V',
   zed=23.0,
   rel=$nrel,
   config='[Ar] 3d3.0 4s2 4p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/V.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3s2 3p6 3d3 4s2'
   configts(2)='3s2 3p6 3d3 4s1 4p1'
   configts(3)='3s2 3p6 3d3 4s1'
   configts(4)='3s2 3p6 3d2 4s2 4p0'
   configts(5)='3s2 3p6 3d4 4s1' 
 /
EOF

cat > Cr.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Cr',
   zed=24.0,
   rel=$nrel,
   config='[Ar] 3d5.0 4s1 4p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Cr.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3s2 3p6 3d5 4s1 '
   configts(2)='3s2 3p6 3d4 4s1 4p1'
   configts(3)='3s2 3p6 3d4 4s1 4p0'
   configts(4)='3s2 3p6 3d4 4s0'
   configts(5)='3s2 3p6 3d6 4s0'
 /
EOF

cat > Mn.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Mn',
   zed=25.0,
   rel=$nrel,
   config='[Ar] 3d5.0 4s2 4p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Mn.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3s2 3p6 3d5 4s2 '
   configts(2)='3s2 3p6 3d5 4s1 4p0'
   configts(3)='3s2 3p6 3d5 4s0 4p0'
   configts(4)='3s2 3p6 3d4 4s2 4p0'
   configts(5)='3s2 3p6 3d4 4s1 4p1'
 /
EOF

cat > Fe.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Fe',
   zed=26.,
   rel=$nrel,
   config='[Ar] 4s2.0 3d6.0 4p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Fe.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3s2 3p6 3d6 4s2'
   configts(2)='3s2 3p6 3d6 4s1 4p0'
   configts(3)='3s2 3p6 3d6 4s1 4p1'
   configts(4)='3s2 3p6 3d7 4s1'
   configts(5)='3s2 3p6 3d7 4s0 4p1'
 /
EOF

cat > Co.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Co',
   zed=27.,
   rel=$nrel,
   config='[Ar] 4s2 3d7 4p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Co.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3s2 3p6 3d7 4s2 4p0'
   configts(2)='3s2 3p6 3d7 4s1 4p0'
   configts(3)='3s2 3p6 3d7 4s0 4p0'
   configts(4)='3s2 3p6 3d8 4s1'
   configts(5)='3s2 3p6 3d8 4s0 4p0'
 /
EOF

cat > Ni.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ni',
   zed=28.,
   rel=$nrel,
   config='[Ar] 4s2 3d8 4p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ni.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3s2 3p6 3d8 4s2'
   configts(2)='3s2 3p6 3d8 4s1 4p0'
   configts(3)='3s2 3p6 3d8 4s1 4p0.5'
   configts(4)='3s2 3p6 3d9 4s1'
   configts(5)='3s2 3p6 3d7.5 4s2 4p0'
 /
EOF

cat > Cu.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Cu',
   zed=29.,
   rel=$nrel,
   config='[Ar] 3d9.5 4s1.5 4p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Cu.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3s2 3p6 3d9.5 4s1.5'
   configts(2)='3s2 3p6 3d9.5 4s1 4p0'
   configts(3)='3s2 3p6 3d10 4s1 4p0'
   configts(4)='3s2 3p6 3d10 4s0 4p0'
   configts(5)='3s2 3p6 3d9  4s1 4p0'
 /
EOF

cat > Zn.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Zn',
   zed=30.,
   rel=$nrel,
   config='[Ar] 3d10. 4s2. 4p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Zn.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='3s2 3p6 3d10 4s2'
   configts(2)='3s2 3p6 3d10 4s1 4p0'
   configts(3)='3s2 3p6 3d10 4s0 4p1 '
   configts(4)='3s2 3p6 3d9.5 4s2. 4p0'
   configts(5)='3s2 3p6 3d9 4s2. 4p0'
 /
EOF

cat > Ga.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ga',
   zed=31.,
   rel=$nrel,
   config='[Ar] 3d10.0 4s2.0 4p1.0 4d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ga.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3d10.0 4s2 4p1'
   configts(2)='3d10.0 4s2 4p0 4d0'
   configts(3)='3d10.0 4s1 4p2'
   configts(4)='3d10.0 4s1 4p1 4d0'
   configts(5)='3d10.0 4s0 4p3'
 /
EOF

cat > Ge.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ge',
   zed=32.,
   rel=$nrel,
   config='[Ar] 3d10.0 4s2.0 4p2.0 4d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ge.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='3d10 4s2 4p2'
   configts(2)='3d10 4s2 4p1 4d0'
   configts(3)='3d10 4s2 4p0 4d0'
   configts(4)='3d10 4s1 4p2 4d0'
   configts(5)='3d10 4s1 4p3'
 /
EOF

cat > As.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='As',
   zed=33.,
   rel=$nrel,
   config='[Ar] 3d10.0 4s2.0 4p3.0 4d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/As.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='3d10 4s2 4p3'
   configts(2)='3d10 4s2 4p2 4d0'
   configts(3)='3d10 4s2 4p1 4d0'
   configts(4)='3d10 4s1 4p3 4d0'
   configts(5)='3d10 4s1 4p4'
 /
EOF

cat > Se.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Se',
   zed=34.,
   rel=$nrel,
   config='[Ar] 3d10.0 4s2.0 4p4.0 4d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Se.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4s2 4p4 3d10'
   configts(2)='4s2 4p3 3d10'
   configts(3)='4s1 4p5 3d10'
   configts(4)='4s1 4p4 3d10'
   configts(5)='4s1 4p3 3d10'
 /
EOF

cat > Br.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Br',
   zed=35.,
   rel=$nrel,
   config='[Ar] 3d10.0 4s2.0 4p5.0 4d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Br.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='3d10 4s2 4p5'
   configts(2)='3d10 4s2 4p4 4d0'
   configts(3)='3d10 4s1 4p5 4d0'
   configts(4)='3d10 4s1 4p4'
   configts(5)='3d10 4s1 4p6'
 /
EOF

cat > Kr.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Kr',
   zed=36.0,
   rel=$nrel,
   config='[Ar] 3d10 4s2 4p6.00 4d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Kr.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4s2 4p6 3d10'
   configts(2)='4s2 4p5 3d10'
   configts(3)='4s1 4p6 3d10'
   configts(4)='4s1 4p5 3d10'
   configts(5)='4s2 4p4 3d10'
 /
EOF

cat > Rb.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Rb',
   zed=37.0,
   rel=$nrel,
   config='[Kr] 4d-2.0 5s1 5p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Rb.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4s2 4p6 5s1  '
   configts(2)='4s2 4p6 5s0 5p1 '
   configts(3)='4s2 4p6 5s0 5p0 '
   configts(4)='4s2 4p6 5s0.5  '
   configts(5)='4s2 4p6 5s0.5 5p0 4d0.5'
 /
EOF

cat > Sr.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Sr',
   zed=38.0,
   rel=$nrel,
   config='[Kr] 4d0.0 5s2 5p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Sr.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4s2 4p6 5s2'
   configts(2)='4s2 4p6 5s1.5'
   configts(3)='4s2 4p6 5s1 5p1'
   configts(4)='4s2 4p6 5s1 5p0'
   configts(5)='4s2 4p6 5s1.75 5p0 4d0.25'
 /
EOF

cat > Y.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Y',
   zed=39.0,
   rel=$nrel,
   config='[Kr] 4d1.0 5s2 5p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Y.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4s2 4p6 4d1 5s2'
   configts(2)='4s2 4p6 4d1 5s1 5p1'
   configts(3)='4s2 4p6 4d1 5s1 5p0'
   configts(4)='4s2 4p6 4d0 5s2 5p0'
   configts(5)='4s2 4p6 4d2 5s1'
 /
EOF

cat > Zr.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Zr',
   zed=40.0,
   rel=$nrel,
   config='[Kr] 4d2.0 5s2 5p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Zr.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4s2 4p6 4d2 5s2'
   configts(2)='4s2 4p6 4d2 5s1 5p1'
   configts(3)='4s2 4p6 4d2 5s1 5p0'
   configts(4)='4s2 4p6 4d1 5s2 5p0'
   configts(5)='4s2 4p6 4d3 5s1'
 /
EOF

cat > Nb.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Nb',
   zed=41.0,
   rel=$nrel,
   config='[Kr] 4d4.0 5s1 5p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Nb.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4s2 4p6 4d4 5s1'
   configts(2)='4s2 4p6 4d4 5s0 5p1'
   configts(3)='4s2 4p6 4d4 5s0 5p0'
   configts(4)='4s2 4p6 4d3 5s2'
   configts(5)='4s2 4p6 4d5 5s0'
 /
EOF

cat > Mo.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Mo',
   zed=42.0,
   rel=$nrel,
   config='[Kr] 4d5.0 5s1 5p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Mo.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4s2 4p6 4d5 5s1'
   configts(2)='4s2 4p6 4d5 5s0 5p0'
   configts(3)='4s2 4p6 4d6 5s0'
   configts(4)='4s2 4p6 4d4 5s2' 
   configts(5)='4s2 4p6 4d4 5s1 5p0'
 /
EOF

cat > Tc.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Tc',
   zed=43.0,
   rel=$nrel,
   config='[Kr] 4d5.0 5s2 5p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Tc.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4s2 4p6 4d5 5s2'
   configts(2)='4s2 4p6 4d5 5s1 5p1'
   configts(3)='4s2 4p6 4d5 5s1 5p0'
   configts(4)='4s2 4p6 4d4 5s2'
   configts(5)='4s2 4p6 4d6 5s1'
 /
EOF

cat > Ru.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ru',
   zed=44.,
   rel=$nrel,
   config='[Kr] 4d6.0 5s2.0 5p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ru.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4s2 4p6 4d6 5s2'
   configts(2)='4s2 4p6 4d6 5s1 5p0'
   configts(3)='4s2 4p6 4d6 5s0 5p1'
   configts(4)='4s2 4p6 4d7 5s1 5p0'
   configts(5)='4s2 4p6 4d5 5s2 5p0'
 /
EOF

cat > Rh.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Rh',
   zed=45.,
   rel=$nrel,
   config='[Kr] 4d8. 5s1.0 5p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Rh.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4s2 4p6 4d8 5s1',
   configts(2)='4s2 4p6 4d8 5s0 5p0',
   configts(3)='4s2 4p6 4d7 5s2 5p0',
   configts(4)='4s2 4p6 4d7 5s1 5p1',
   configts(5)='4s2 4p6 4d7 5s0 5p0',
 /
EOF

cat > Pd.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Pd',
   zed=46.,
   rel=$nrel,
   config='[Kr] 4d10. 5s0. 5p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Pd.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4s2 4p6 4d10 5s0.0'
   configts(2)='4s2 4p6 4d9.5 5s0.5'
   configts(3)='4s2 4p6 4d9.5 5s0 5p0.5'
   configts(4)='4s2 4p6 4d9 5s1 5p0'
   configts(5)='4s2 4p6 4d9 5s0 5p1'
 /
EOF

cat > Ag.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ag',
   zed=47.,
   rel=$nrel,
   config='[Kr] 4d9.5 5s1.5 5p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ag.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4s2 4p6 4d9.5 5s1.5 5p0',
   configts(2)='4s2 4p6 4d10 5s1 ',
   configts(3)='4s2 4p6 4d8.5 5s1.5 5p1.0',
   configts(4)='4s2 4p6 4d9 5s2 5p0',
   configts(5)='4s2 4p6 4d10. 5s0 5p0',
 /
EOF

cat > Cd.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Cd',
   zed=48.,
   rel=$nrel,
   config='[Kr] 4d9.5 5s2.0 5p0.5',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Cd.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4s2 4p6 4d9.5 5s2 5p0.5 ',
   configts(2)='4s2 4p6 4d9.5 5s2 5p0',
   configts(3)='4s2 4p6 4d10  5s2 5p0',
   configts(4)='4s2 4p6 4d10  5s1 5p0',
   configts(5)='4s2 4p6 4d9   5s2 5p0',
 /
EOF

cat > In.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='In',
   zed=49.,
   rel=$nrel,
   config='[Kr] 4d10.0 5s2.0 5p1.0 5d-1',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/In.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p1'
   configts(2)='4d10 5s2 5p0 5d0'
   configts(3)='4d10 5s2 5p0 5d0'
   configts(4)='4d10 5s1 5p2'
   configts(5)='4d10 5s1 5p1 5d0'
 /
EOF

cat > Sn.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Sn',
   zed=50.,
   rel=$nrel,
   config='[Kr] 4d10.0 5s2.0 5p2.0 5d-1',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Sn.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p2'
   configts(2)='4d10 5s2 5p1 5d0'
   configts(3)='4d10 5s2 5p0'
   configts(4)='4d10 5s1 5p3'
   configts(5)='4d10 5s1 5p2 5d0'
 /
EOF

cat > Sb.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Sb',
   zed=51.,
   rel=$nrel,
   config='[Kr] 4d10.0 5s2.0 5p3.0 5d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Sb.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p3'
   configts(2)='4d10 5s2 5p2 5d0'
   configts(3)='4d10 5s2 5p2 5d0.5'
   configts(4)='4d10 5s1 5p3 5d0'
   configts(5)='4d10 5s1 5p3 5d0.5'
 /
EOF

cat > Te.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Te',
   zed=52.,
   rel=$nrel,
   config='[Kr] 4d10.0 5s2.0 5p4.00 5d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Te.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p4'
   configts(2)='4d10 5s2 5p3 5d0'
   configts(3)='4d10 5s2 5p2'
   configts(4)='4d10 5s1 5p5'
   configts(5)='4d10 5s1 5p4 5d0'
 /
EOF

cat > I.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='I',
   zed=53.,
   rel=$nrel,
   config='[Kr] 4d10.0 5s2.0 5p5.0 5d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/I.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p5'
   configts(2)='4d10 5s2 5p4 5d0'
   configts(3)='4d10 5s2 5p3 5d0'
   configts(4)='4d10 5s2 5p2 5d0'
   configts(5)='4d10 5s1 5p4'
 /
EOF

cat > Xe.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Xe',
   zed=54.,
   rel=$nrel,
   config='[Kr] 4d10.0 5s2.0 5p6.0 5d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Xe.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p6'
   configts(2)='4d10 5s2 5p5 5d0.5'
   configts(3)='4d10 5s2 5p5 5d0'
   configts(4)='4d10 5s1 5p6 5d0'
   configts(5)='4d10 5s1 5p5 5d0.5'
 /
EOF

cat > Cs.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Cs',
   zed=55.0,
   rel=$nrel,
   config='[Xe] 5d0.0 6s1 6p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Cs.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='5s2 5p6 6s1'
   configts(2)='5s2 5p6 6s0 6p1'
   configts(3)='5s2 5p6 6s0.5 6p0'
   configts(4)='5s2 5p6 6s0.5 6p0.5'
   configts(5)='5s2 5p6 6s0 6p0 5d1'
 /
EOF

cat > Ba.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ba',
   zed=56.0,
   rel=$nrel,
   config='[Xe] 5d0.0 6s2 6p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ba.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='5s2 5p6 6s2'
   configts(2)='5s2 5p6 6s1.5 6p0'
   configts(3)='5s2 5p6 6s1 6p1'
   configts(4)='5s2 5p6 6s0.5 6p1'
   configts(5)='5s2 5p6 6s1. 6p0 5d0'
 /
EOF

cat > La.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='La',
   zed=57.0,
   rel=$nrel,
   config='[Xe] 4f0 5d1.0 6s1.5 6p0.5',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/La.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p6 6s2 6p0 5d1 4f0 '
   configts(2)='4d10 5s2 5p6 6s1.5 6p0.0  5d1 4f0 '
   configts(3)='4d10 5s2 5p6 6s1 6p0. 5d1 4f0 '
   configts(4)='4d10 5s2 5p6 6s1 6p0. 5d0 4f0.6 '
   configts(5)='4d10 5s2 5p6 6s1 6p1. 5d0 4f0 '
 /
EOF

cat > La.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='La',
   zed=57.0,
   rel=$nrel,
   config='[Xe] 4f0 5d1.0 6s1.5 6p0.5',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/La.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='5s2  5p6 6s2   6p0   5d1 4f0 '
   configts(2)='5s2  5p6 6s1.5 6p0.5 5d1 4f0 '
   configts(3)='5s2  5p6 6s1   6p0   5d1 4f0 '
   configts(4)='5s2  5p6 6s0   6p0   5d1 4f0 '
   configts(5)='5s2  5p6 6s1   6p1   5d1 4f0 '
 /
EOF

cat > Ce.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ce',
   zed=58.0,
   rel=$nrel,
   config='[Xe] 4f1 5d1.0 6s2. 6p0.',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ce.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10. 5s2 5p6 6s2 6p0 5d1 4f1 '
   configts(2)='4d10. 5s2 5p6 6s2 6p1 5d0 4f1 '
   configts(3)='4d10. 5s2 5p6 6s1 6p0 5d1 4f0.5 '
   configts(4)='4d10. 5s2 5p6 6s1 6p0 5d1 4f0.5 '
   configts(5)='4d10. 5s2 5p6 6s1 6p1 5d1 4f0.5'
 /
EOF

#cat > Ce.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
# &input
#   title='Ce',
#   zed=58.0,
#   rel=$nrel,
#   config='[Xe] 4f1 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Ce.$fct-spfn-rrkjus_psl.1.0.0.UPF',
#   nconf=5,
#   frozen_core=$frozen_core,
#   configts(1)='5s2 5p6 6s2 6p0 5d1 4f1 '
#   configts(2)='5s2 5p6 6s2 6p1 5d0 4f1 '
#   configts(3)='5s2 5p6 6s1 6p0 5d1 4f0.5 '
#   configts(4)='5s2 5p6 6s1 6p0 5d1 4f0.5 '
#   configts(5)='5s2 5p6 6s1 6p1 5d1 4f0.5'
# /
#EOF

cat > Pr.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Pr',
   zed=59.0,
   rel=$nrel,
   config='[Xe] 4f3.0 5d0.0 6s2. 6p0.',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Pr.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10. 5s2 5p6 6s2 6p0 5d1 4f2 '
   configts(2)='4d10. 5s2 5p6 6s2 6p1 5d0 4f2 '
   configts(3)='4d10. 5s2 5p6 6s1 6p0 5d1 4f1.5 '
   configts(4)='4d10. 5s2 5p6 6s1 6p0 5d1 4f1.5 '
   configts(5)='4d10. 5s2 5p6 6s1 6p1 5d1 4f1.5'
 /
EOF

#cat > Pr.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
# &input
#   title='Pr',
#   zed=59.0,
#   rel=$nrel,
#   config='[Xe] 4f3.0 5d0.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Pr.$fct-spfn-rrkjus_psl.1.0.0.UPF',
#   nconf=5,
#   frozen_core=$frozen_core,
#   configts(1)='5s2 5p6 6s1.5 6p0.5  5d0 4f3 '
#   configts(2)='5s2 5p6 6s2 6p0 5d0 4f3 '
#   configts(3)='5s2 5p6 6s2 6p0. 5d1 4f2 '
#   configts(4)='5s2 5p6 6s2 6p0. 5d0 4f2 '
#   configts(5)='5s2 5p6 6s1 6p0. 5d0 4f3.4 '
# /
#EOF

cat > Nd.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Nd',
   zed=60.0,
   rel=$nrel,
   config='[Xe] 4f4.0 5d0.0 6s2. 6p0.',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Nd.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p6 6s2 6p0 5d0 4f4'
   configts(2)='4d10 5s2 5p6 6s1.5 6p0.5 5d0 4f4'
   configts(3)='4d10 5s2 5p6 6s2 6p0. 5d1 4f3'
   configts(4)='4d10 5s2 5p6 6s2 6p0. 5d0 4f3'
   configts(5)='4d10 5s2 5p6 6s1 6p0. 5d0 4f4.4'
 /
EOF

#cat > Nd.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
# &input
#   title='Nd',
#   zed=60.0,
#   rel=$nrel,
#   config='[Xe] 4f4.0 5d0.0 6s1.5 6p0.5',
##   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Nd.$fct-spfn-rrkjus_psl.1.0.0.UPF',
#   nconf=5,
#   frozen_core=$frozen_core,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d0 4f4'
#   configts(2)='5s2 5p6 6s2 6p0 5d0 4f4'
#   configts(3)='5s2 5p6 6s2 6p0. 5d1 4f3'
#   configts(4)='5s2 5p6 6s2 6p0. 5d0 4f3'
#   configts(5)='5s2 5p6 6s1 6p0. 5d0 4f4.4'
# /
#EOF

cat > Pm.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Pm',
   zed=61.0,
   rel=$nrel,
   config='[Xe] 4f5.0 5d0.0 6s1.5 6p0.5',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Pm.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p6 6s1.5 6p0.5 5d0 4f5 '
   configts(2)='4d10 5s2 5p6 6s2 6p0 5d0 4f5 '
   configts(3)='4d10 5s2 5p6 6s2 6p0. 5d1 4f4 '
   configts(4)='4d10 5s2 5p6 6s2 6p0. 5d0 4f4 '
   configts(5)='4d10 5s2 5p6 6s1 6p0. 5d0 4f5.5 '
 /
EOF

#cat > Pm.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
# &input
#   title='Pm',
#   zed=61.0,
#   rel=$nrel,
#   config='[Xe] 4f5.0 5d0.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Pm.$fct-spfn-rrkjus_psl.1.0.0.UPF',
#   nconf=5,
#   frozen_core=$frozen_core,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d0 4f5 '
#   configts(2)='5s2 5p6 6s2 6p0 5d0 4f5 '
#   configts(3)='5s2 5p6 6s2 6p0. 5d1 4f4 '
#   configts(4)='5s2 5p6 6s2 6p0. 5d0 4f4 '
#   configts(5)='5s2 5p6 6s1 6p0. 5d0 4f5.5 '
# /
#EOF
#
cat > Sm.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Sm',
   zed=62.0,
   rel=$nrel,
   config='[Xe] 4f5.5 5d0.5 6s2. 6p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Sm.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p6 6s2 6p0 5d0.5 4f5.5 '
   configts(2)='4d10 5s2 5p6 6s2 6p0 5d0 4f6 '
   configts(3)='4d10 5s2 5p6 6s2 6p0. 5d1 4f5 '
   configts(4)='4d10 5s2 5p6 6s2 6p0. 5d0 4f5.5 '
   configts(5)='4d10 5s2 5p6 6s1 6p1. 5d0 4f5.5 '
 /
EOF

#cat > Sm.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
# &input
#   title='Sm',
#   zed=62.0,
#   rel=$nrel,
#   config='[Xe] 4f6.0 5d0.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Sm.$fct-spfn-rrkjus_psl.1.0.0.UPF',
#   nconf=5,
#   frozen_core=$frozen_core,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d0 4f6'
#   configts(2)='5s2 5p6 6s2 6p0 5d0 4f6'
#   configts(3)='5s2 5p6 6s2 6p0. 5d1 4f5'
#   configts(4)='5s2 5p6 6s2 6p0. 5d0 4f5'
#   configts(5)='5s2 5p6 6s1 6p0. 5d0 4f6.5'
# /
#EOF

cat > Eu.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Eu',
   zed=63.0,
   rel=$nrel,
   config='[Xe] 4f7.0 5d0.0 6s2. 6p0.',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Eu.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p6 6s2 6p0 5d0 4f7 '
   configts(2)='4d10 5s2 5p6 6s1.5 6p0.5 5d0 4f7 '
   configts(3)='4d10 5s2 5p6 6s2 6p0. 5d1 4f6 '
   configts(4)='4d10 5s2 5p6 6s2 6p0. 5d0 4f6 '
   configts(5)='4d10 5s2 5p6 6s1 6p0. 5d0 4f7.5 '
 /
EOF

#cat > Eu.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
# &input
#   title='Eu',
#   zed=63.0,
#   rel=$nrel,
#   config='[Xe] 4f7.0 5d0.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Eu.$fct-spfn-rrkjus_psl.1.0.0.UPF',
#   nconf=5,
#   frozen_core=$frozen_core,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d0 4f7 '
#   configts(2)='5s2 5p6 6s2 6p0 5d0 4f7 '
#   configts(3)='5s2 5p6 6s2 6p0. 5d1 4f6 '
#   configts(4)='5s2 5p6 6s2 6p0. 5d0 4f6 '
#   configts(5)='5s2 5p6 6s1 6p0. 5d0 4f7.5 '
# /
#EOF

cat > Gd.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Gd',
   zed=64.0,
   rel=$nrel,
   config='[Xe] 4f8.0 5d0.0 6s2. 6p0.',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Gd.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p6 6s2 6p0 5d0 4f8'
   configts(2)='4d10 5s2 5p6 6s1.5 6p0.5 5d0 4f8'
   configts(3)='4d10 5s2 5p6 6s2 6p0. 5d1 4f7'
   configts(4)='4d10 5s2 5p6 6s2 6p0. 5d0 4f7'
   configts(5)='4d10 5s2 5p6 6s1 6p0. 5d0 4f8.5'
 /
EOF

#cat > Gd.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
# &input
#   title='Gd',
#   zed=64.0,
#   rel=$nrel,
#   config='[Xe] 4f8.0 5d0.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Gd.$fct-spfn-rrkjus_psl.1.0.0.UPF',
#   nconf=5,
#   frozen_core=$frozen_core,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d0 4f8'
#   configts(2)='5s2 5p6 6s2 6p0 5d0 4f8'
#   configts(3)='5s2 5p6 6s2 6p0. 5d1 4f7'
#   configts(4)='5s2 5p6 6s2 6p0. 5d0 4f7'
#   configts(5)='5s2 5p6 6s1 6p0. 5d0 4f8.5'
# /
#EOF

cat > Tb.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Tb',
   zed=65.0,
   rel=$nrel,
   config='[Xe] 4f9 5d0.0 6s2. 6p0.',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Tb.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p6 6s2 6p0 5d0 4f9 '
   configts(2)='4d10 5s2 5p6 6s1.5 6p0.5 5d0 4f9 '
   configts(3)='4d10 5s2 5p6 6s1 6p0. 5d0 4f9 '
   configts(4)='4d10 5s2 5p6 6s1 6p0. 5d1 4f8.0 '
   configts(5)='4d10 5s2 5p6 6s0 6p0. 5d0 4f10.0 '
 /
EOF

#cat > Tb.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
# &input
#   title='Tb',
#   zed=65.0,
#   rel=$nrel,
#   config='[Xe] 4f9 5d0.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Tb.$fct-spfn-rrkjus_psl.1.0.0.UPF',
#   nconf=5,
##   frozen_core=$frozen_core,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d0 4f9 '
#   configts(2)='5s2 5p6 6s2 6p0 5d0 4f9 '
#   configts(3)='5s2 5p6 6s2 6p0. 5d1 4f8 '
#   configts(4)='5s2 5p6 6s2 6p0. 5d0 4f8 '
#   configts(5)='5s2 5p6 6s1 6p0. 5d0 4f9.5 '
# /
#EOF

cat > Dy.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Dy',
   zed=66.0,
   rel=$nrel,
   config='[Xe] 4f10.0 5d0.0 6s2. 6p0.',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Dy.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p6 6s2 6p0 5d0 4f10 '
   configts(2)='4d10 5s2 5p6 6s1.5 6p0.5 5d0 4f10 '
   configts(3)='4d10 5s2 5p6 6s1 6p0. 5d0 4f10 '
   configts(4)='4d10 5s2 5p6 6s1 6p0. 5d1 4f9.0 '
   configts(5)='4d10 5s2 5p6 6s0 6p0. 5d0 4f10.5 '
 /
EOF

#cat > Dy.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
# &input
#   title='Dy',
#   zed=66.0,
#   rel=$nrel,
#   config='[Xe] 4f10.0 5d0.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Dy.$fct-spfn-rrkjus_psl.1.0.0.UPF',
#   nconf=5,
#   frozen_core=$frozen_core,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d0 4f10 '
#   configts(2)='5s2 5p6 6s2 6p0 5d0 4f10 '
#   configts(3)='5s2 5p6 6s2 6p0. 5d1 4f9 '
#   configts(4)='5s2 5p6 6s2 6p0. 5d0 4f9 '
#   configts(5)='5s2 5p6 6s1 6p0. 5d0 4f10.5 '
# /
#EOF

cat > Ho.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ho',
   zed=67.0,
   rel=$nrel,
   config='[Xe] 4f11.0 5d0.0 6s2. 6p0.',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ho.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p6 6s2 6p0 5d0 4f11 '
   configts(2)='4d10 5s2 5p6 6s1.5 6p0.5 5d0 4f11 '
   configts(3)='4d10 5s2 5p6 6s1 6p0. 5d0 4f11 '
   configts(4)='4d10 5s2 5p6 6s1 6p0. 5d1 4f10.0 '
   configts(5)='4d10 5s2 5p6 6s0 6p0. 5d0 4f12.0 '
 /
EOF

#cat > Ho.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
# &input
#   title='Ho',
#   zed=67.0,
#   rel=$nrel,
#   config='[Xe] 4f11.0 5d0.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Ho.$fct-spfn-rrkjus_psl.1.0.0.UPF',
#   nconf=5,
#   frozen_core=$frozen_core,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d0 4f11'
#   configts(2)='5s2 5p6 6s2 6p0 5d0 4f11'
#   configts(3)='5s2 5p6 6s2 6p0. 5d1 4f10'
#   configts(4)='5s2 5p6 6s2 6p0. 5d0 4f10'
#   configts(5)='5s2 5p6 6s1 6p0. 5d0 4f11.5'
# /
#EOF

cat > Er.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Er',
   zed=68.0,
   rel=$nrel,
   config='[Xe] 4f12.0 5d0.0 6s2.0 6p0.',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Er.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p6 6s2 6p0 5d0 4f12 '
   configts(2)='4d10 5s2 5p6 6s1.5 6p0.5 5d0 4f12 '
   configts(3)='4d10 5s2 5p6 6s1 6p0. 5d0 4f12 '
   configts(4)='4d10 5s2 5p6 6s1 6p0. 5d1 4f11.0 '
   configts(5)='4d10 5s2 5p6 6s0 6p0. 5d0 4f13.0 '
 /
EOF

#cat > Er.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
# &input
#   title='Er',
#   zed=68.0,
#   rel=$nrel,
#   config='[Xe] 4f12.0 5d0.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Er.$fct-spfn-rrkjus_psl.1.0.0.UPF',
#   nconf=5,
#   frozen_core=$frozen_core,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d0 4f12 '
#   configts(2)='5s2 5p6 6s2 6p0 5d0 4f12 '
#   configts(3)='5s2 5p6 6s2 6p0. 5d1 4f11 '
#   configts(4)='5s2 5p6 6s2 6p0. 5d0 4f11 '
#   configts(5)='5s2 5p6 6s1 6p0. 5d0 4f12.5 '
# /
#EOF

cat > Tm.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Tm',
   zed=69.0,
   rel=$nrel,
   config='[Xe] 4f13.0 5d0.0 6s2. 6p0.',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Tm.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p6 6s2 6p0 5d0 4f13 '
   configts(2)='4d10 5s2 5p6 6s1.5 6p0.5 5d0 4f13 '
   configts(3)='4d10 5s2 5p6 6s1 6p0. 5d0 4f13 '
   configts(4)='4d10 5s2 5p6 6s1 6p0. 5d1 4f12.0 '
   configts(5)='4d10 5s2 5p6 6s0 6p0. 5d0 4f12.0 '
 /
EOF

#cat > Tm.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
# &input
#   title='Tm',
#   zed=69.0,
#   rel=$nrel,
#   config='[Xe] 4f13.0 5d0.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Tm.$fct-spfn-rrkjus_psl.1.0.0.UPF',
#   nconf=5,
#   frozen_core=$frozen_core,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d0 4f13'
#   configts(2)='5s2 5p6 6s2 6p0 5d0 4f13'
#   configts(3)='5s2 5p6 6s2 6p0. 5d1 4f12'
#   configts(4)='5s2 5p6 6s2 6p0. 5d0 4f12'
#   configts(5)='5s2 5p6 6s1 6p0. 5d0 4f13.5'
# /
#EOF

cat > Yb.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Yb',
   zed=70.0,
   rel=$nrel,
   config='[Xe] 4f14.0 5d0.0 6s2. 6p0.',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Yb.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p6 6s2 6p0 5d0 4f14'
   configts(2)='4d10 5s2 5p6 6s1.5 6p0.5 5d0 4f14'
   configts(3)='4d10 5s2 5p6 6s2 6p0. 5d1 4f13'
   configts(4)='4d10 5s2 5p6 6s2 6p0. 5d0 4f13'
   configts(5)='4d10 5s2 5p6 6s1 6p0. 5d0 4f14'
 /
EOF

#cat > Yb.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
# &input
#   title='Yb',
#   zed=70.0,
#   rel=$nrel,
#   config='[Xe] 4f14.0 5d0.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
#   file_pseudo='$psdir/Yb.$fct-spfn-rrkjus_psl.1.0.0.UPF',
#   nconf=5,
#   frozen_core=$frozen_core,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d0 4f14'
#   configts(2)='5s2 5p6 6s2 6p0 5d0 4f14'
#   configts(3)='5s2 5p6 6s2 6p0. 5d1 4f13'
#   configts(4)='5s2 5p6 6s2 6p0. 5d0 4f13'
#   configts(5)='5s2 5p6 6s1 6p0. 5d0 4f14'
# /
#EOF

cat > Lu.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Lu',
   zed=71.0,
   rel=$nrel,
   config='[Xe] 4f14.0 5d1.0 6s2. 6p0.',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Lu.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4d10 5s2 5p6 6s2 6p0 5d1 4f14 '
   configts(2)='4d10 5s2 5p6 6s1.5 6p0.5 5d1 4f14 '
   configts(3)='4d10 5s2 5p6 6s1 6p0. 5d1 4f14 '
   configts(4)='4d10 5s2 5p6 6s1 6p0. 5d2 4f13.0 '
   configts(5)='4d10 5s2 5p6 6s2 6p0. 5d1 4f13.0 '
 /
EOF

#cat > Lu.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
# &input
#   title='Lu',
#   zed=71.0,
#   rel=$nrel,
#   config='[Xe] 4f14.0 5d1.0 6s1.5 6p0.5',
#   iswitch=2,
# /
# &test
##   file_pseudo='$psdir/Lu.$fct-spfn-rrkjus_psl.1.0.0.UPF',
#   nconf=5,
#   frozen_core=$frozen_core,
#   configts(1)='5s2 5p6 6s1.5 6p0.5 5d1 4f14'
#   configts(2)='5s2 5p6 6s2 6p0 5d1 4f14'
#   configts(3)='5s2 5p6 6s2 6p0. 5d2 4f13'
#   configts(4)='5s2 5p6 6s2 6p0. 5d1 4f13'
#   configts(5)='5s2 5p6 6s1 6p0. 5d1 4f14'
# /
#EOF

cat > Hf.$fct-spdfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Hf',
   zed=72.0,
   rel=$nrel,
   config='[Xe] 4f14 5d2.0 6s2 6p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Hf.$fct-spdfn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4d10 4f14 5s2 5p6 5d2 6s2'
   configts(2)='4d10 4f14 5s2 5p6 5d2 6s1 6p1'
   configts(3)='4d10 4f14 5s2 5p6 5d2 6s1 6p0'
   configts(4)='4d10 4f14 5s2 5p6 5d2 6s0 6p0'
   configts(5)='4d10 4f14 5s2 5p6 5d1 6s2 6p0'
 /
EOF

cat > Hf.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Hf',
   zed=72.0,
   rel=$nrel,
   config='[Xe] 4f14 5d2.0 6s2 6p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Hf.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4f14 5s2 5p6 5d2 6s2'
   configts(2)='4f14 5s2 5p6 5d2 6s1 6p1'
   configts(3)='4f14 5s2 5p6 5d2 6s1 6p0'
   configts(4)='4f14 5s2 5p6 5d2 6s0 6p0'
   configts(5)='4f14 5s2 5p6 5d1 6s2 6p0'
 /
EOF

cat > Ta.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ta',
   zed=73.0,
   rel=$nrel,
   config='[Xe] 4f14 5d3.0 6s2 6p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ta.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4f14 5s2 5p6 5d3 6s2 6p0'
   configts(2)='4f14 5s2 5p6 5d3 6s1 6p1'
   configts(3)='4f14 5s2 5p6 5d3 6s1 6p0'
   configts(4)='4f14 5s2 5p6 5d2 6s2 6p0'
   configts(5)='4f14 5s2 5p6 5d2 6s1 6p1'
 /
EOF

cat > W.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='W',
   zed=74.0,
   rel=$nrel,
   config='[Xe] 4f14 5d4.0 6s2 6p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/W.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4f14 5s2 5p6.0 5d4 6s2'
   configts(2)='4f14 5s2 5p6.0 5d4 6s1 6p1'
   configts(3)='4f14 5s2 5p6.0 5d4 6s1 6p0'
   configts(4)='4f14 5s2 5p6.0 5d3 6s2 6p0'
   configts(5)='4f14 5s2 5p6.0 5d3 6s1'
 /
EOF

cat > Re.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Re',
   zed=75.0,
   rel=$nrel,
   config='[Xe] 4f14 5d5.0 6s2 6p0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Re.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4f14 5s2 5p6 5d5 6s2'
   configts(2)='4f14 5s2 5p6 5d5 6s1.5 6p0'
   configts(3)='4f14 5s2 5p6 5d5 6s1 6p1'
   configts(4)='4f14 5s2 5p6 5d4 6s2'
   configts(5)='4f14 5s2 5p6 5d6 6s1'
 /
EOF

cat > Os.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Os',
   zed=76.,
   rel=$nrel,
   iswitch=2,
   config='[Xe] 4f14.0 5d6.0 6s2.0 6p0.0',
 /
 &test
   file_pseudo='$psdir/Os.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4f14 5s2 5p6 5d6 6s2 6p0',
   configts(2)='4f14 5s2 5p6 5d6 6s1 6p1',
   configts(3)='4f14 5s2 5p6 5d6 6s1 6p0',
   configts(4)='4f14 5s2 5p6 5d5 6s2 6p0',
   configts(5)='4f14 5s2 5p6 5d7 6s1 6p0',
 /
EOF

cat > Ir.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ir',
   zed=77.,
   rel=$nrel,
   config='[Xe] 4f14.0 5d7.0 6s2.0 6p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ir.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4f14 5s2 5p6 6s2 6p0 5d7'
   configts(2)='4f14 5s2 5p6 6s1.5 6p0 5d7'
   configts(3)='4f14 5s2 5p6 6s1.5 6p0.3 5d7'
   configts(4)='4f14 5s2 5p6 6s2 6p0.0 5d6'
   configts(5)='4f14 5s2 5p6 6s2 6p1.0 5d6'
 /
EOF

cat > Pt.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Pt',
   zed=78.,
   rel=$nrel,
   config='[Xe] 4f14 5d9.0 6s1.0 6p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Pt.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='4f14 5s2 5p6 5d9 6s1 6p0'
   configts(2)='4f14 5s2 5p6 5d9 6s0 6p0'
   configts(3)='4f14 5s2 5p6 5d10 6s0'
   configts(4)='4f14 5s2 5p6 5d8 6s1 6p0'
   configts(5)='4f14 5s2 5p6 5d8 6s1 6p1'
 /
EOF

cat > Au.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Au',
   zed=79.,
   rel=$nrel,
   config='[Xe] 4f14 5d10.0 6s1.0 6p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Au.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='4f14 5s2 5p6 5d10. 6s1 6p0',
   configts(2)='4f14 5s2 5p6 5d10. 6s0 6p0.5',
   configts(3)='4f14 5s2 5p6 5d10. 6s0 6p0',
   configts(4)='4f14 5s2 5p6 5d9.5 6s1 ',
   configts(5)='4f14 5s2 5p6 5d9.5 6s1 6p0',
 /
EOF

cat > Hg.$fct-spn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Hg',
   zed=80.0,
   rel=$nrel,
   config='[Xe] 4f14. 5d10 6s2 6p-1',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Hg.$fct-spn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='5s2 5p6 5d10 6s2'
   configts(2)='5s2 5p6 5d10 6s1 6p0'
   configts(3)='5s2 5p6 5d10 6s0 6p1'
   configts(4)='5s2 5p6 5d9  6s2 6p0'
   configts(5)='5s2 5p6 5d9  6s1 6p0'
 /
EOF

cat > Tl.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Tl',
   zed=81.,
   rel=$nrel,
   config='[Xe] 4f14.0 5d10.0 6s2.0 6p1.0 6d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Tl.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='5d10 6s2 6p1'
   configts(2)='5d10 6s2 6p0 6d0'
   configts(3)='5d10 6s1 6p1'
   configts(4)='5d10 6s1 6p2'
   configts(5)='5d10 6s1 6p0'
 /
EOF

cat > Pb.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Pb',
   zed=82.0,
   rel=$nrel,
   config='[Xe] 4f14 5d10 6s2 6p2 6d-1',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Pb.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='5d10. 6s2 6p2'
   configts(2)='5d10. 6s2 6p1 6d0'
   configts(3)='5d10. 6s2 6p0 6d0'
   configts(4)='5d10. 6s1 6p3'
   configts(5)='5d10. 6s1 6p2 6d0'
 /
EOF

cat > Bi.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Bi',
   zed=83.,
   rel=$nrel,
   config='[Xe] 4f14.0 5d10.0 6s2.0 6p3.0 6d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Bi.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='5d10 6s2 6p3'
   configts(2)='5d10 6s2 6p2 6d0'
   configts(3)='5d10 6s2 6p1.0 6d0'
   configts(4)='5d10 6s1 6p3.0 6d0'
   configts(5)='5d10 6s1 6p4.0 '
 /
EOF

cat > Po.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Po',
   zed=84.,
   rel=$nrel,
   config='[Xe] 4f14.0 5d10.0 6s2.0 6p4.0 6d-2',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Po.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='5d10 6s2 6p4',
   configts(3)='5d10 6s2 6p3',
   configts(2)='5d10 6s1 6p4',
   configts(4)='5d10 6s1 6p5',
   configts(5)='5d10 6s1 6p3',
 /
EOF

cat > At.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='At',
   zed=85.,
   rel=$nrel,
   config='[Xe] 4f14.0 5d10.0 6s2.0 6p5.0 6d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/At.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='5d10 6s2 6p5'
   configts(2)='5d10 6s2 6p4'
   configts(3)='5d10 6s2 6p3'
   configts(4)='5d10 6s1 6p5'
   configts(5)='5d10 6s1 6p6'
 /
EOF

cat > Rn.$fct-dn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Rn',
   zed=86.,
   rel=$nrel,
   config='[Xe] 4f14.0 5d10.0 6s2.0 6p6.0 6d-2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Rn.$fct-dn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='5d10 6s2 6p6'
   configts(2)='5d10 6s2 6p5'
   configts(3)='5d10 6s2 6p4'
   configts(4)='5d10 6s1 6p6'
   configts(5)='5d10 6s1 6p5'
 /
EOF

cat > Fr.$fct-spdn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Fr',
   zed=87.,
   rel=$nrel,
   config='[Xe] 4f14.0 5d10.0 6s2.0 6p6.0 6d-2.0 7s1.0 7p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Fr.$fct-spdn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='5d10 6s2 6p6 7s1.0'
   configts(2)='5d10 6s2 6p6 7s0.0'
   configts(3)='5d10 6s2 6p5 7s1.0 7p0.0'
   configts(4)='5d10 6s2 6p6 7s0.5'
   configts(5)='5d10 6s2 6p5 7s0.5'
 /
EOF

cat > Ra.$fct-spdn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ra',
   zed=88.,
   rel=$nrel,
   config='[Xe] 4f14.0 5d10.0 6s2.0 6p6.0 6d-2.0 7s2.0 7p0.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ra.$fct-spdn-rrkjus_psl.1.0.0.UPF',
   nconf=5
   frozen_core=$frozen_core,
   configts(1)='5d10 6s2 6p6 7s2.0'
   configts(2)='5d10 6s2 6p6 7s1.0'
   configts(3)='5d10 6s2 6p5 7s2.0 7p0.0'
   configts(4)='5d10 6s2 6p6 7s1.5'
   configts(5)='5d10 6s2 6p5 7s1.5'
 /
EOF

cat > Ac.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Ac',
   zed=89.0,
   rel=$nrel,
   config='[Rn] 6d1.0 7s2.0 7p0. 5f-1',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Ac.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='6s2 6p6 7s2 7p0 6d1 '
   configts(2)='6s2 6p6 7s1.5 7p0.0  6d1 '
   configts(3)='6s2 6p6 7s1 7p0. 6d1 5f0 '
   configts(4)='6s2 6p6 7s1 7p0. 6d0 5f0.6 '
   configts(5)='6s2 6p6 7s1 7p1. 6d0 5f0. '
 /
EOF

cat > Th.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Th',
   zed=90.0,
   rel=$nrel,
   config='[Rn] 6d2.0 7s2.0 7p0. 5f0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Th.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='6s2 6p6 7s2 7p0 6d1 5f1 '
   configts(2)='6s2 6p6 7s2 7p0. 6d0 5f1 '
   configts(3)='6s2 6p6 7s2 7p0. 6d1 5f0 '
   configts(4)='6s2 6p6 7s1 7p0. 6d1 5f1 '
   configts(5)='6s2 6p6 7s1 7p0. 6d0 5f2 '
 /
EOF

cat > Pa.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Pa',
   zed=91.0,
   rel=$nrel,
   config='[Rn] 6d1.0 7s2.0 7p0. 5f2.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Pa.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='6s2 6p6 7s2 7p0 6d1 5f2 '
   configts(2)='6s2 6p6 7s2 7p0. 6d0 5f2 '
   configts(3)='6s2 6p6 7s2 7p0. 6d1 5f1 '
   configts(4)='6s2 6p6 7s1 7p0. 6d1 5f2.0 '
   configts(5)='6s2 6p6 7s1 7p0. 6d0 5f3.0 '
 /
EOF

cat > U.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='U',
   zed=92.0,
   rel=$nrel,
   config='[Rn] 6d1.0 7s2.0 7p0. 5f3.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/U.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='6s2 6p6 7s2 7p0 6d1 5f3'
   configts(2)='6s2 6p6 7s1.5 7p0.0 6d1 5f3'
   configts(3)='6s2 6p6 7s1 7p0. 6d1 5f2'
   configts(4)='6s2 6p6 7s1 7p0. 6d0 5f3.6'
   configts(5)='6s2 6p6 7s1 7p1. 6d1 5f2'
 /
EOF

cat > Np.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Np',
   zed=93.0,
   rel=$nrel,
   config='[Rn] 6d1.0 7s2.0 7p0. 5f4.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Np.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='6s2 6p6 7s2 7p0 6d1.5 5f3.5 '
   configts(2)='6s2 6p6 7s2 7p0. 6d0 5f4 '
   configts(3)='6s2 6p6 7s2 7p0. 6d1 5f3 '
   configts(4)='6s2 6p6 7s1 7p0. 6d1 5f4.0 '
   configts(5)='6s2 6p6 7s1 7p0. 6d1 5f4 '
 /
EOF

cat > Pu.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Pu',
   zed=94.0,
   rel=$nrel,
   config='[Rn] 6d0.0 7s2.0 7p0. 5f6.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Pu.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='6s2 6p6 7s2 7p0 6d1.5 5f4.5 '
   configts(2)='6s2 6p6 7s2 7p0. 6d0 5f5 '
   configts(3)='6s2 6p6 7s2 7p0. 6d1 5f4 '
   configts(4)='6s2 6p6 7s1 7p0. 6d1 5f5.0 '
   configts(5)='6s2 6p6 7s1 7p0. 6d1 5f5 '
 /
EOF

cat > Am.$fct-spfn-rrkjus_psl.1.0.0.test.in << EOF
 &input
   title='Am',
   zed=95.0,
   rel=$nrel,
   config='[Rn] 6d0.0 7s2.0 7p0. 5f7.0',
   iswitch=2,
 /
 &test
   file_pseudo='$psdir/Am.$fct-spfn-rrkjus_psl.1.0.0.UPF',
   nconf=5,
   frozen_core=$frozen_core,
   configts(1)='6s2 6p6 7s2 7p0 6d0 5f6 '
   configts(2)='6s2 6p6 7s1.5 7p0.5  6d0 5f6 '
   configts(3)='6s2 6p6 7s1 7p1. 6d0 5f6 '
   configts(4)='6s2 6p6 7s1 7p0. 6d0 5f6.6 '
   configts(5)='6s2 6p6 7s1 7p0. 6d1 5f6. '
 /
EOF

